print('--DESAFIO 004--')
f = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(f))
print('Tem somente espaços?',  f.isspace())
print('É apenas numérico?', f.isnumeric())
print('É apenas alfabético?', f.isalpha())
print('É numérico e alfabético?', f.isalnum())
print('Está em minúsculo?', f.islower())
print('Está em maiscúlo?', f.isupper())
print('Está capitalizada?', f.istitle())